<a href="https://colab.research.google.com/github/xodud5654/PDM05/blob/main/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [8]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
# data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape[])

SyntaxError: ignored

## Print rows

In [4]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# data.shape # Error!
# convert to a numpy array
data = asarray(data)
# step through rows
for row in range(data.shape[0]):
	print(data[row])

[1 2 3]
[4 5 6]


## Print columns

In [7]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col])

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


---

## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [9]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None)
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [10]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum()
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=1 Row-Wise Operation (수평으로)

In [11]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum()
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


---

## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [DIY: 도전하기]

- 3차원 배열을 리스트로부터 만드시오.
- [참고: numpy_sum_axis](http://taewan.kim/post/numpy_sum_axis/)

In [12]:
# Make 3d-array in numpy

data = [[1,2,3], [4,5,6]]



AttributeError: ignored